//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nabaztag.WebTts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nabaztag.WebTts.Resources.Tts", typeof(Tts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicaitonSettings {
            get {
                return ResourceManager.GetString("ApplicaitonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application path.
        /// </summary>
        public static string ApplicationPath {
            get {
                return ResourceManager.GetString("ApplicationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Cognitive Services settings.
        /// </summary>
        public static string AzureSettings {
            get {
                return ResourceManager.GetString("AzureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Text to Speach.
        /// </summary>
        public static string BackToTts {
            get {
                return ResourceManager.GetString("BackToTts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Cognitive Services Endpoint.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Cognitive Services Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabaztag pynab IP Address.
        /// </summary>
        public static string NabaztagAddress {
            get {
                return ResourceManager.GetString("NabaztagAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabaztag pynab Port.
        /// </summary>
        public static string NabaztagPort {
            get {
                return ResourceManager.GetString("NabaztagPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred voice.
        /// </summary>
        public static string PrefferedShortName {
            get {
                return ResourceManager.GetString("PrefferedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say it on Nabaztag.
        /// </summary>
        public static string TtsSayIt {
            get {
                return ResourceManager.GetString("TtsSayIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Speech.
        /// </summary>
        public static string TtsTitle {
            get {
                return ResourceManager.GetString("TtsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to say?.
        /// </summary>
        public static string TtsWhatToSay {
            get {
                return ResourceManager.GetString("TtsWhatToSay", resourceCulture);
            }
        }
    }
}
